### ISSUE TITLE
[FEAT] Follow git config format

### ISSUE THREAD

**Issue by b4nst** [b4nst/turbogit#1]
**Is your feature request related to a problem? Please describe.**

As the tool has a strong connection with git, it would be wise to follow the same standards for the configuration.

**Describe the solution you'd like**

```toml
[user]
name = "foo"
email = "foo@bar.com"
```

instead of 
```toml
username = "foo"
email = "foo@bar.com"
```

**Additional context**
